name: Minecart
version: 2.1.0
description: plugin responsible for managing the payment orders made by the Minecart
author: [SnowRunescape]
website: https://minecart.com.br

main: br.com.minecart.Minecart

commands:
    minecart:
        description: list version and commands
        aliases: []
    mykeys:
        description: list with all the vip keys the player has to activate
        aliases: [minhaskeys]
    redeemcash:
        description: redeem cash purchased
        aliases: [resgatarcash]
    redeemvip:
        description: redeem vip purchased
        aliases: [resgatarvip]